name: Deploy to Salesforce

on:
  push:
    branches:
      - main  # Déclenche le pipeline lors d'un push sur la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilisation d'une machine virtuelle Ubuntu pour l'exécution

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Salesforce CLI
      uses: amitsingh-007/sfdx-action@v1
      with:
        sfdx-cli-version: 'latest'

    - name: Authenticate to Salesforce
      run: |
        echo ${{ secrets.SF_USERNAME }} > sfdx-auth-url.txt
        sfdx force:auth:sfdxurl:store --sfdxurlfile sfdx-auth-url.txt --setdefaultusername

    - name: Deploy code to Salesforce
      run: |
        sfdx force:source:deploy -p force-app/main/default --targetusername ${{ secrets.SF_USERNAME }}
        sfdx force:org:open  # Ouvre l'org dans le navigateur après le déploiement