name: Deploy to Salesforce

on:
  push:
    branches:
      - main  # Déclenche le pipeline lors d'un push sur la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilisation d'une machine virtuelle Ubuntu pour l'exécution

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Salesforce CLI
      run: |
        # Installer Salesforce CLI (SFDX)
        curl -fsSL https://developer.salesforce.com/media/sfdx-cli/debian/apt-key.asc | sudo tee /etc/apt/trusted.gpg.d/sfdx-cli.asc
        echo "deb https://developer.salesforce.com/media/sfdx-cli/debian/ stable main" | sudo tee /etc/apt/sources.list.d/sfdx-cli.list
        sudo apt-get update
        sudo apt-get install -y sfdx-cli

    - name: Authenticate to Salesforce
      run: |
        # Utiliser l'URL d'authentification Salesforce pour se connecter
        echo ${{ secrets.SF_AUTH_URL }} > sfdx-auth-url.txt
        sfdx force:auth:sfdxurl:store --sfdxurlfile sfdx-auth-url.txt --setdefaultusername ${{ secrets.SF_USERNAME }}

    - name: Deploy code to Salesforce
      run: |
        sfdx force:source:deploy -p force-app/main/default --targetusername ${{ secrets.SF_USERNAME }}
        sfdx force:org:open  # Ouvre l'org dans le navigateur après le déploiement