name: Deploy and Validate Metadata

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install SFDX CLI and sfdx-git-delta plugin # Ce package va vous permettre de faire un delta entre votre branche et la branch ciblé. Voici la documentation : https://github.com/scolladon/sfdx-git-delta
        run: |
          npm install -g @salesforce/cli@latest
          echo "y" | npm install sfdx-git-delta@3.3.0 -g

      - name: 'Authentification Salesforce'
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > sfdx-auth-url.txt
          sfdx force:auth:sfdxurl:store --sfdxurlfile sfdx-auth-url.txt --setdefaultusername --setalias my-org
        shell: bash

      - name: 'Install sfdx-git-delta'
        run: npm install -g sfdx-git-delta@3.3.0
        shell: bash

      - name: 'Verify sfdx-git-delta installation'
        run: |
          echo "Checking sfdx-git-delta installation..."
          which sfdx-git-delta || echo "sfdx-git-delta not found!"
          sfdx-git-delta --version || echo "sfdx-git-delta execution failed!"
        shell: bash

      - name: 'Generate metadata delta pull request'
        run: npx sfdx-git-delta --from=origin/main --to=HEAD --metadata --targetdir=.temp
        shell: bash

      - name: 'Déployer les métadonnées sur la branch main'
        if: github.ref == 'refs/heads/main'
        run:  sfdx force:source:deploy -p .temp --targetusername ${{ secrets.SF_USERNAME }}
        
      - name: 'Ouvrir l’org Salesforce'
        run: |
          sfdx force:org:open
        if: github.ref == 'refs/heads/main'
