name: Deploy and Validate Metadata

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install SFDX CLI and sfdx-git-delta plugin # Ce package va vous permettre de faire un delta entre votre branche et la branch ciblé. Voici la documentation : https://github.com/scolladon/sfdx-git-delta
        run: |
              npm install -g @salesforce/cli@latest
              sfdx plugins:install sfdx-git-delta

      - name: 'Authentification Salesforce'  # Vous devez avoir une connexion avec Salesforce pour pouvoir deployer le code à la dernière étape.
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > sfdx-auth-url.txt
          sfdx force:auth:sfdxurl:store --sfdxurlfile sfdx-auth-url.txt --setdefaultusername --setalias my-org
        shell: bash    

              # Étape 4: Crée un répertoire temporaire pour stocker le package.xml généré
      - name: Create temporary directory for package.xml
        run: mkdir -p .temp

              # Étape 5: Générer le package.xml delta entre la branche actuelle et main
      - name: Generate metadata delta pull request
        run: |
              # Utilisation de npx pour appeler sfdx-git-delta si installé localement
              sfdx sgd:source:delta --to HEAD --from origin/main --output .temp
              echo "--- package.xml generated with added and modified metadata ---"
              cat .temp/package.xml

      - name: 'Déployer les métadonnées sur la branch main'
        if: github.ref == 'refs/heads/main'
        run:  sfdx force:source:deploy -p .temp --targetusername ${{ secrets.SF_USERNAME }}
        
      - name: 'Ouvrir l’org Salesforce'
        run: |
          sfdx force:org:open
        if: github.ref == 'refs/heads/main'
